name: docker-build

on:
  push:
    branches: [ "test-docker-build" ]
  workflow_dispatch:

jobs:

  publish-docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: merusso/netwait
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: merusso
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
